version: 2
# Tell CircleCI to use this workflow
workflows:
  version: 2
  default:
    jobs:
      - "python-3.7"

jobs:
  "python-3.7":
    working_directory: ~/esm-collection-spec
    docker:
      - image: circleci/python:3.7

    steps:
      # Get our data and merge with upstream
      - checkout

      - run:
          name: Install Link Validators
          command: |
            sudo apt-get install curl software-properties-common
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g remark-cli remark-validate-links

      - run:
          name: Install Validator
          command: python -m pip install esmcol-validator --user
      - run:
          name: Validate
          command: |
            remark -f -u validate-links .
            cd collection-spec/examples
            esmcol-validator sample-glade-cmip6-netcdf-collection.json
            esmcol-validator sample-pangeo-cmip6-collection.json
            esmcol-validator --esmcol-spec-dirs ../json-schema simple-collection-with-catalog-dict.json
