version: 2
# Tell CircleCI to use this workflow
workflows:
  version: 2
  default:
    jobs:
      - "python-3.7"

jobs:
  "python-3.7":
    docker:
      - image: circleci/python:3.7

    steps:
      # Get our data and merge with upstream
      - checkout

      - run: # install dev dependencies
          name: Install Dev Dependencies
          command: pip install pytest codecov pytest-cov --user
      - run:
          name: Install Package
          command: pip install -e . --user
      - run:
          name: Running Tests
          command: pytest --junitxml=test-reports/junit.xml --cov=./ --verbose
      - run:
          name: Code Coverage
          command: |
            echo "[Upload coverage]"
            codecov
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
